# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inventlist < Formula
  desc "InventList CLI — command your whole stack from the terminal"
  homepage "https://inventlist.com/tools/cli"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.7.0/inventlist_Darwin_x86_64.tar.gz"
      sha256 "080ac98a6629031cbfcd0a0fa53433480386de3c1b3af099d2df14bd99e0500d"

      define_method(:install) do
        bin.install "inventlist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.7.0/inventlist_Darwin_arm64.tar.gz"
      sha256 "c452d4f3c97b5a4074da268f0f8b6dd35543f4692030b884b8752b6efa31366b"

      define_method(:install) do
        bin.install "inventlist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.7.0/inventlist_Linux_x86_64.tar.gz"
      sha256 "4f5f3018d944dc8b3dc34a99a8faf7ced85915b2133d70d2f4e8d6f920eabcba"
      define_method(:install) do
        bin.install "inventlist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.7.0/inventlist_Linux_arm64.tar.gz"
      sha256 "32dfcdf3865a1828fe3b0871ff3103d27b2a5f8a101d3636c56003fa89f4f9a5"
      define_method(:install) do
        bin.install "inventlist"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/inventlist version")
  end
end
