# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inventlist < Formula
  desc "InventList CLI — command your whole stack from the terminal"
  homepage "https://inventlist.com/tools/cli"
  version "0.42.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.42.1/inventlist_Darwin_x86_64.tar.gz"
      sha256 "37cfa597c7e89ae8710f9ea35b985134c2edf402f7f61d37473203bb1ecfefc9"

      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
        bin.install_symlink "inventlist" => "road"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.42.1/inventlist_Darwin_arm64.tar.gz"
      sha256 "e966b94e14a7942088355d3bcb3a7154fbcf9da04f0f9fa2491208fd3908ccce"

      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
        bin.install_symlink "inventlist" => "road"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.42.1/inventlist_Linux_x86_64.tar.gz"
      sha256 "f9251bc58c3a6815df91e417524d75e8650c7f7a8217aca061ea07aebc007e6c"
      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
        bin.install_symlink "inventlist" => "road"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.42.1/inventlist_Linux_arm64.tar.gz"
      sha256 "bc26440a907645ee23bed2ff3f12ebecc40957b79197a0f138bdb700828c7b33"
      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
        bin.install_symlink "inventlist" => "road"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/inventlist version")
  end
end
