# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inventlist < Formula
  desc "InventList CLI — command your whole stack from the terminal"
  homepage "https://inventlist.com/tools/cli"
  version "0.33.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.33.0/inventlist_Darwin_x86_64.tar.gz"
      sha256 "f3800bde6cda5516997e9018a255b263fc82dfe81d1168496d2a5ac2e3adfea6"

      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.33.0/inventlist_Darwin_arm64.tar.gz"
      sha256 "99ee29915628204a8eecc180efcb3d1eb289d9cab34899b270b8ffe4afeb1e68"

      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.33.0/inventlist_Linux_x86_64.tar.gz"
      sha256 "f5bd0f69be05c6adc5de25c5aa9688d5a89e0b59a99332d5c6c596ce91d9b577"
      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.33.0/inventlist_Linux_arm64.tar.gz"
      sha256 "0eb9b72d774989f83e6d0d9a95a51952cd22a9775564561e9f3b9022ea0222da"
      define_method(:install) do
        bin.install "inventlist"
        # CLI flavors (plan 28 · WS5): `np` is the nodepad-first entry point.
        # Same binary, name-keyed — invoking it as `np` flips the surface.
        bin.install_symlink "inventlist" => "np"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/inventlist version")
  end
end
